## Задание на повторение материала

In [183]:
import numpy as np

### Задание 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [184]:
a = np.array([i for i in range(12, 24)])
a, len(a)

(array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), 12)

### Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [185]:
a1 = a.reshape(12, 1)
a2 = a.reshape(6, 2)
a3 = a.reshape(2, 6)
a4 = a.reshape(3, 4)
a5 = a.reshape(4, 3)
a1, a2, a3, a4, a5

(array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

### Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [186]:
b1 = a.reshape(12, -1)
b2 = a.reshape(6, -1)
b3 = a.reshape(2, -1)
b4 = a.reshape(-1, 4)
b5 = a.reshape(-1, 3)
b1, b2, b3, b4, b5

(array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

### Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет, это двумерный массив. См форму массивов a и a1...

In [187]:
print(f'Одномерный массив a: {a.shape}')
print(f'Двумерный массив a1: {a1.shape}')

Одномерный массив a: (12,)
Двумерный массив a1: (12, 1)


### Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [188]:
a = np.random.randn(3, 4)
a

array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112,  0.31424733]])

In [189]:
b = a.flatten()
b

array([ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
       -0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753,
       -1.01283112,  0.31424733])

In [190]:
a.size == b.size

True

### Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [191]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [192]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Элементы массивов a и b совпадают, но размерности массивов отличаются. Массив b - двумерный.

In [193]:
print(f'Массив a: Число измерений = {a.ndim}; Форма = {a.shape}')
print(f'Массив b: Число измерений = {b.ndim}; Форма = {b.shape}')

Массив a: Число измерений = 1; Форма = (10,)
Массив b: Число измерений = 2; Форма = (1, 10)


### Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [194]:
# считаю количество строк для массивов a и b
ncols = 2
size = 10
nrows_a = int((size // 2 - 1) / 2)
nrows_b = int(size // 2 - nrows_a)
nrows_a, nrows_b

(2, 3)

In [195]:
a = np.zeros((nrows_a, ncols))
a

array([[0., 0.],
       [0., 0.]])

In [196]:
b = np.ones((nrows_b, ncols))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [197]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [198]:
c.size

10

### Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [199]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [200]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [201]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [202]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [203]:
print(f'У матрицы B:\n\tФорма = {B.shape}\n\tКоличество элементов = {B.size}')

У матрицы B:
	Форма = (4, 4)
	Количество элементов = 16


In [204]:
if (np.linalg.det(B) == 0):
    print('Определитель матрицы B равен нулю. Построить обратную матрицу невозможно.')
else:
    print('Обратная матрица B:')
    np.linalg.inv(B)

Определитель матрицы B равен нулю. Построить обратную матрицу невозможно.


### Задание 10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [205]:
np.random.seed(42)

### Задание 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [206]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [207]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [208]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [209]:
print(f'Определитель матрицы D = {np.linalg.det(D)}')
print(f'Ранг матрицы D         = {np.linalg.matrix_rank(D)}')

Определитель матрицы D = -28511999.999999944
Ранг матрицы D         = 4


In [210]:
D_inv = np.linalg.inv(D)
print(f'Обратная матрица D_inv:')
D_inv

Обратная матрица D_inv:


array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [211]:
D_inv[ D_inv < 0] = 0
D_inv[ D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [212]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])